---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
  cloud: ospcloud
   #server: *
   filters:
    vm_state: active
   register: osp_instance_del
 
- name: show server info
   msg: "{{ result.osp_instance_del }}"
  
  
  
  
  #- name: Delete instances
   
