---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
   cloud: ospcloud
   filters:
    vm_state: active
  register: osp_instance_del
 
- name: show server info
  debug:
   msg: "{{ item.server }}"
  loop: "{{ osp_instance_del.results }}"
  
  
  
  #- name: Delete instances
   
