---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
   cloud: ospcloud
  register: osp_instance_del
 
- name: show server info
  debug:
   msg: "{{ osp_instance_del.openstack_servers }}"
  
  
  
  #- name: Delete instances
   
