---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
   cloud: ospcloud
   region_name: RegionOne
  register: osp_instance_del
 
- name: Delete instances
  os_server:
   cloud: ospcloud
   state: absent
   name: "{{ item.name }}"
  with_items: "{{ osp_intance_del.openstack_servers }}"
