---
- name: Intall the require packages
  package:
   name: "{{ item }}"
   state: latest
  loop: 
   "{{ packages }}" 

- name: Start Load balancer at boot
  service:
   name: "{{ package[1] }}"
   enabled: yes

- name: Configure "{{ package[1] }}"
  template:
   src: haproxy.cfg.j2
   dest: /etc/haproxy/haproxy.cfg
  notify: restart {{ package[1] }}
