---
- name: Intall haproxy
  package:
   name: haproxy
   state: latest

- name: Start Load balancer at boot
  service:
   name: haproxy
   enabled: yes

- name: Start Load balacer serivice
  service:
   name: haproxy
   state: started

- name: Configure haproxy
  template:
   src: haproxy.cfg.j2
   dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
