---
- name: Intall ha_proxy
  package:
   name: ha_proxy
   state: latest

- name: Start Load balancer at boot
  service:
   name: ha_proxy
   enabled: yes

- name: Start Load balacer serivice
  service:
   name: ha_proxy
   state: started

- name: Configure ha_proxy
  template:
   src: haproxy.cfg.j2
   dest: /etc/haproxy/haproxy.cfg
  notify: restart ha_proxy
