---

# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    cloud: os_server
    name: "{{ item.value.name }}"
    state: "{{item.value.state }}"
    image: "{{ item.value.image }}"
    key_name: "{{ item.value.key_name }}"
    flavor: "{{ item.value.flavor }}"
    security_group: "{{ item.value.securit_group }}"
    meta:
     group: "{{ item.value.meta[0] }}"
     deployment_name: "{{ item.value.meta[1] }}"
    network: "{{ }}"
   with_dict: "{{ osp_servers }}"

- name: Add floating IP to Servers
   name: "  

#- name: Wait for server to be available
