---
# tasks file for db-tier
- name: install {{ possgr }} database
  yum:
    name: postgresql-server
    state: latest
  notify: "enable {{ possgr }} at boot"
 
- name: initialize postgres
  shell: 
    postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION
    
- name: start postgress service
  service:
    name: "{{ possgr }}"
    state: started
