---
# tasks file for db-tier
  - name: install packages
    yum:
      name: postgresql-server
      state: latest
  
  - name: enable postgesql at boot
    service:
      name: postgresql
      enabled: yes
      
  - name: tell user to finish setting up postgres
    debug:
      msg: "Either uncomment the postgres setup or manually login and initialize"

 # only run the next 2 tasks once!
#  - name: initilize postgressql
#    command: postgresql-setup initdb
#  - name: initilize postgres some more
#    command: chkconfig postgresql on
  - name: start postgress service
    service:
      name: postgresql.service
      state: started

- name: deploy apache
  hosts: apps
  gather_facts: false
  become: true
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: latest
  - name: enable apache at boot
    service:
      name: httpd
      enabled: yes
#  - name: start apache
#    service:
#      name: httpd
#      state: started
