---
# Initial, common, system setup steps
- name: Clean up repos
  shell: yum clean all


- name: enable repos
  template:
    src: repos_template.repo
    dest: /etc/yum.repos.d/repos_template.repo
    mode: 0644

- name: install base tools and packages
  yum:
   name: "{{ item }}" 
   state: latest
  with_items:
   - httpie
   - python-pip
