---
# Initial, common, system setup steps
- name: enable repos
  template:
    src: open_three-tier-app.repo
    dest: /etc/yum.repos.d/repos_template.j2
    mode: 0644

- name: install base tools and packages
  yum:
   name: "{{ item }}" 
   state: latest
  with_items:
   - httpie
   - python-pip
